# Traefik configuration file
api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: odoo@gmail.com
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

log:
  level: INFO

accessLog: {}
